### ISSUE TITLE
Tracking issue: Library testing

### ISSUE THREAD

**Issue by tushar-deepsource** [deepsourcelabs/depend#122]
This issue tracks the things that we need to test and verify with the library

- [ ] The correct features are being fetched when pulling the `chrono` library
- [ ] We're not fetching any dev dependencies in Poetry
- [ ] We're not fetching any dev dependencies in NPM
